### ISSUE TITLE
npm run build fails to minify

### ISSUE THREAD

**Issue by HughLaird** [pusher/feeds-client-js#29]
I have a react app that cannot build a release version due to the feeds client failing to minify.

![image](https://user-images.githubusercontent.com/38730150/39991693-41f43f18-5768-11e8-8d9e-afe02f7f9a45.png)

Can you offer any help/ideas? Thanks.

**Comment by callum-oakley** [comment]
Looks like `pusher-platform-js` has a dependency on `p-cancelable` which isn't transpiled to es5, so ends up in the bundle with syntax that uglify doesn't like. `p-cancelable` has been removed as a dependency from `pusher-platform-js` so an internal upgrade to a later version should fix this. Will keep you updated.

**Comment by HughLaird** [comment]
Many thanks for your replies. I have followed your advice and update react-scripts, which has fixed the issue for now. I will be looking forward to seeing your dependency fix in a future build. 

Again thanks very much for the quick turn around on this.

**Comment by callum-oakley** [comment]
@HughLaird I've published what I think should be a fix to this to `@pusher/feeds@0.10.1` (we're gradually moving all our repositories over to the `@pusher` org on npm)

If you could confirm that this all works as expected, I'll close this issue and update the documentation to point to the new repository :) Thans for letting us know about the issue!

**Comment by HughLaird** [comment]
@callum-oakley Thanks for this. I'm not using yarn so how would I switch over from having previously installed the pusher-feeds-client, to the new @pusher file structure? I have already installed the @pusher/feeds@0.10.1 package as you suggested, but I need to update my import to reflect the package change? Not sure what to change the import to (I'm kinda new to node)!

**Comment by callum-oakley** [comment]
Yes, you'll need to import `from '@pusher/feeds'` or `require('@pusher/feeds')` (depending on if you're using es6 module syntax or not.

**Comment by HughLaird** [comment]
Perfect. Thanks. This appears to be functioning and building without any errors now. I reverted back to the 1.1.4 version of react-scripts to test and all works/builds fine. Many thanks.
